kind: pipeline
name: kernel_ci

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: default
    image: ubuntu:latest
    commands:
      - apt update && apt install -y bison flex bc curl wget build-essential zstd git zip python libssl-dev
      - git clone https://github.com/dragonJACson/aarch64-linux-gcc /drone/aarch64-linux-gcc
      - git clone https://github.com/dragonJACson/arm-linux-gnueabi-gcc /drone/arm-linux-gnueabi-gcc
      - mkdir out
      - rm -rf out/arch/arm64/boot
      - make O=out ARCH=arm64 lineageos_jason_defconfig
      - make -j${KJOBS} O=out ARCH=arm64 CROSS_COMPILE="/drone/aarch64-linux-gcc/bin/aarch64-linux-" CROSS_COMPILE_ARM32="/drone/arm-linux-gnueabi-gcc/bin/arm-linux-gnueabi-"

