name: Kernel Building CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: update and install
      run: sudo apt update && sudo apt install -y bison flex bc curl wget build-essential zstd git zip python libssl-dev
    - name: clone repos
      run: sudo mkdir /action && sudo git clone https://github.com/dragonJACson/aarch64-linux-gcc /action/aarch64-linux-gcc && sudo git clone https://github.com/dragonJACson/arm-linux-gnueabi-gcc /action/arm-linux-gnueabi-gcc
    - name: init for kernel building
      run: mkdir out && rm -rf out/arch/arm64/boot && make O=out ARCH=arm64 lineageos_jason_defconfig
    - name: build kernel
      run: make -j${KJOBS} O=out ARCH=arm64 CROSS_COMPILE="/action/aarch64-linux-gcc/bin/aarch64-linux-" CROSS_COMPILE_ARM32="/action/arm-linux-gnueabi-gcc/bin/arm-linux-gnueabi-"
